import { chromium } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
await mkdir('artifacts/qa', { recursive: true });
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const report = { pages: [], accessibility: [], errors: [], performance: {}, interactions: [] };
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
const page = await context.newPage();
page.on('pageerror', error => report.errors.push(error.message));
page.on('console', message => { if (message.type() === 'error' && !message.text().includes('503')) report.errors.push(message.text()); });
for (const [path, name] of [['/', 'home-desktop'], ['/en', 'home-english'], ['/expertises', 'expertises'], ['/projets/maison-charlet', 'project'], ['/contact', 'contact'], ['/agence', 'about']]) {
  const response = await page.goto('http://localhost:3000' + path, { waitUntil: 'networkidle' });
  await page.evaluate(() => document.fonts.ready);
  assert.equal(response.status(), 200, path);
  assert.equal(await page.locator('h1').count(), 1);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, path + ' overflow');
  report.pages.push(path);
  await page.locator('img[loading="lazy"]').evaluateAll(images => images.forEach(image => { image.loading = 'eager'; }));
  await page.evaluate(() => Promise.all([...document.images].map(image => image.decode().catch(() => {}))));
  await page.screenshot({ path: `artifacts/qa/${name}.png`, fullPage: true });
  if (path === '/') await page.screenshot({ path: 'artifacts/qa/home-viewport.png' });
  if (path === '/' || path === '/contact') {
    const result = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
    report.accessibility.push({ path, viewport: 'desktop', violations: result.violations.map(v => ({ id: v.id, impact: v.impact, description: v.description, nodes: v.nodes.map(n => ({ html: n.html, summary: n.failureSummary })) })) });
  }
  if (path === '/') report.performance = await page.evaluate(() => ({ navigation: performance.getEntriesByType('navigation').map(n => ({ domContentLoadedMs: Math.round(n.domContentLoadedEventEnd), loadMs: Math.round(n.loadEventEnd), transferBytes: n.transferSize })), resources: performance.getEntriesByType('resource').map(r => ({ url: new URL(r.name).pathname, transferred: r.transferSize, size: r.decodedBodySize })), fontLoaded: document.fonts.check('500 16px Manrope') }));
}
await page.setViewportSize({ width: 390, height: 844 });
await page.goto('http://localhost:3000/', { waitUntil: 'networkidle' });
await page.locator('img[loading="lazy"]').evaluateAll(images => images.forEach(image => { image.loading = 'eager'; }));
await page.evaluate(() => Promise.all([...document.images].map(image => image.decode().catch(() => {}))));
await page.screenshot({ path: 'artifacts/qa/home-mobile.png', fullPage: true });
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
await page.getByRole('button', { name: 'Ouvrir le menu' }).click();
assert.equal(await page.locator('#mobile-nav').isVisible(), true);
await page.keyboard.press('Escape'); assert.equal(await page.locator('#mobile-nav').isVisible(), false);
report.interactions.push('Mobile menu opens and closes with Escape');
const mobileAxe = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
report.accessibility.push({ path: '/', viewport: 'mobile', violations: mobileAxe.violations.map(v => ({ id: v.id, impact: v.impact, nodes: v.nodes.map(n => ({ html: n.html, summary: n.failureSummary })) })) });
for (const width of [320, 768, 1024]) {
  await page.setViewportSize({ width, height: 900 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'Home overflow at ' + width);
}
await page.setViewportSize({ width: 390, height: 844 });
await page.goto('http://localhost:3000/contact');
await page.getByRole('textbox', { name: 'Votre nom' }).fill('Test navigateur');
await page.getByRole('textbox', { name: 'Votre email' }).fill('test@example.com');
await page.getByRole('textbox', { name: 'Parlez-nous de votre projet' }).fill('Test local du formulaire, aucun email ne doit être envoyé sans SMTP.');
await page.getByRole('button', { name: 'Envoyer le message' }).click();
await page.waitForFunction(() => document.querySelector('.form-status').textContent.length > 0);
assert.match(await page.locator('.form-status').innerText(), /n’a pas pu être envoyé/);
assert.equal(await page.getByRole('button', { name: 'Envoyer le message' }).isEnabled(), true);
assert.equal(await page.getByRole('textbox', { name: 'Votre nom' }).inputValue(), 'Test navigateur');
report.interactions.push('Missing SMTP shows an honest error and preserves the form');
const access = await readFile('.local/admin-access.txt', 'utf8');
const password = access.match(/Mot de passe : ([^\r\n]+)/)[1];
await page.goto('http://localhost:3000/admin');
await page.getByRole('textbox', { name: 'Adresse email' }).fill('contact@thermidor-agence-web.fr');
await page.getByLabel('Mot de passe').fill(password);
await page.getByRole('button', { name: 'Se connecter' }).click();
await page.waitForURL('**/admin');
await page.setViewportSize({ width: 1440, height: 1000 });
await page.screenshot({ path: 'artifacts/qa/admin.png', fullPage: true });
await page.getByRole('link', { name: 'Ajouter un projet' }).click();
await page.screenshot({ path: 'artifacts/qa/admin-editor.png', fullPage: true });
const adminAxe = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
report.accessibility.push({ path: '/admin/projects/new', viewport: 'desktop', violations: adminAxe.violations.map(v => ({ id: v.id, impact: v.impact, nodes: v.nodes.map(n => ({ html: n.html, summary: n.failureSummary })) })) });
await page.setViewportSize({ width: 390, height: 844 });
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'Admin editor overflow');
report.interactions.push('Admin login and responsive editor work');
await page.getByRole('button', { name: 'Déconnexion' }).click();
await page.waitForURL('**/admin/login');
report.interactions.push('Admin logout works');
const noJS = await browser.newContext({ javaScriptEnabled: false, viewport: { width: 390, height: 844 } });
const staticPage = await noJS.newPage();
await staticPage.goto('http://localhost:3000/');
assert.equal(await staticPage.locator('h1').isVisible(), true);
assert.equal(await staticPage.locator('.service-row').count(), 6);
report.interactions.push('Public content and service links available without JavaScript');
await noJS.close();
await writeFile('artifacts/qa/report.json', JSON.stringify(report, null, 2));
console.log(JSON.stringify(report, null, 2));
await browser.close();
assert.equal(report.errors.length, 0, 'Browser errors');
assert.equal(report.accessibility.flatMap(r => r.violations).length, 0, 'Accessibility violations');
